
services:
  frontend:
    container_name: frontend
    hostname: evmlisa-web-app-frontend
    image: evmlisa-web-app-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://localhost:9273

  backend:
    container_name: backend
    hostname: evmlisa-web-app-backend
    image: evmlisa-web-app-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9273:9273"
    volumes:
      - ./backend:/app